name: Pipeline
on: [push]
env:
  APPLICATION_NAME: app2
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Setting pythond env
        uses: actions/setup-python@v1.1.1
      - name: Install requirement
        run:  pip install --quiet --requirement requirements.txt
      - name: Lint code
        run: |
          flake8 --ignore=E501,E231 *.py
          pylint --disable=C0301 --disable=C0326 *.py
      - name: Run unit tests
        run: |
          python -m unittest --verbose --failfast
      
      
  
